const {chromium}=require('playwright'),assert=require('node:assert/strict'),F=require('../engine');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const ctx=await b.newContext({permissions:['clipboard-read','clipboard-write']});const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const root=process.env.DIRECTOR_URL||'http://127.0.0.1:8765/director_game/';
for(const [width,height] of [[1366,900],[975,800],[390,844],[375,667],[320,568]]){await p.setViewportSize({width,height});await p.goto(root);await p.locator('[data-topic]').first().waitFor();assert.equal(await p.locator('[data-topic]').count(),3);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('[data-topic="manager"]').click();assert((await p.locator('.counter').innerText()).includes('1 / 20'));assert(await p.locator('[data-answer]').last().evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight),`Initial answers fit ${width}`);}
await p.setViewportSize({width:390,height:844});
for(const id of Object.keys(F.topics)){await p.goto(root);await p.locator(`[data-topic="${id}"]`).click();const answers=[];const waitQuestion=async n=>p.waitForFunction(n=>document.body.dataset.screen==='question'&&document.querySelector('.counter')?.textContent.trim()===`${n} / 20`,n);const choose=async(a,n)=>{await p.locator(`[data-answer="${a}"]`).click();if(n<20)await waitQuestion(n+1);else await p.locator('.result-hero').waitFor();};
await choose('a',1);await p.click('#back');assert.equal(await p.locator('[data-answer="a"]').getAttribute('aria-pressed'),'true');await choose('b',1);answers.push('b');for(let n=2;n<=20;n++){assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await p.locator('[data-answer]').last().evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight),`${id} Q${n} choices fit mobile`);const a=['a','c','b'][n%3];answers.push(a);await choose(a,n);}
const r=F.result(id,answers);assert.equal(await p.locator('h1').innerText(),r.title);assert.equal(await p.locator('.dimension').count(),4);assert((await p.locator('.dimension-list').innerText()).length>1000);await p.fill('#nickname','전주월드컵경기장');await p.click('#copy');const text=(await p.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n');assert.equal(text,F.share(id,answers,'전주월드컵경기장'));assert(!text.includes('http'));
await p.click('#revise');assert((await p.locator('.counter').innerText()).includes('20 / 20'));const changed=answers[19]==='a'?'b':'a';answers[19]=changed;await choose(changed,20);assert.equal(await p.locator('h1').innerText(),F.result(id,answers).title);
await p.locator('.answer-review summary').click();await p.locator('[data-revise="0"]').click();assert.equal(await p.locator('[data-answer="b"]').getAttribute('aria-pressed'),'true');for(let n=1;n<=20;n++){await p.click('#next');if(n<20)await waitQuestion(n+1);else await p.locator('.result-hero').waitFor();}assert.equal(await p.locator('h1').innerText(),F.result(id,answers).title);console.log('PASS theme:',id,'20 questions; revise/back preserves later answers; detailed result recalculates; copied content matches');}
await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(Error('blocked'))}}));await p.click('#copy');assert(await p.locator('#copy-fallback').isVisible());await p.fill('#nickname','<script>');await p.click('#copy');assert((await p.locator('#copy-status').innerText()).includes('20자'));await p.screenshot({path:process.env.TEMP+'/football-test-result.png',fullPage:true});await p.click('#choose-topic');assert.equal(await p.locator('[data-topic]').count(),3);await p.screenshot({path:process.env.TEMP+'/football-test-mobile.png',fullPage:true});await p.setViewportSize({width:1366,height:900});await p.screenshot({path:process.env.TEMP+'/football-test-desktop.png',fullPage:true});
await p.goto(root+'admin.html');await p.locator('#share-url').waitFor();const embed=await p.inputValue('#embed-code');assert(embed.includes('allow="clipboard-write"'));const ep=await ctx.newPage();await ep.setContent(embed);await ep.frameLocator('iframe').locator('[data-topic]').first().waitFor();assert.equal(await ep.frameLocator('iframe').locator('[data-topic]').count(),3);assert.equal(await ep.frameLocator('iframe').locator('#copy-embed').count(),0);assert.deepEqual(errors,[]);console.log('PASS: 5 viewports, 60 mobile questions, prior answer editing, 3 report types, copy fallback, real iframe');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
