const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const Quiz=require('../engine.js');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const origin='http://127.0.0.1:8765/player_quiz/';
 const version=JSON.parse(fs.readFileSync('player_quiz/data/manifest.json','utf8')).version;
 const data=JSON.parse(fs.readFileSync(`player_quiz/data/${version}.json`,'utf8'));
 await page.goto(origin+'admin.html');await page.locator('#copy').waitFor();assert.equal(await page.locator('select,[data-choice],#generate').count(),0);
 const shareURL=await page.inputValue('#share-url'),embed=await page.inputValue('#embed-code');assert.equal(shareURL,origin);assert(!embed.includes('#q='));
 await page.click('#copy-embed');assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),embed);
 await page.click('#copy');assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),shareURL);
 await page.goto(shareURL);await page.locator('.option').first().waitFor();assert((await page.locator('.question-top').innerText()).includes('난이도 하 · 5문제'));assert.equal(await page.locator('#hints .hint').count(),5);assert.equal(await page.locator('#start').count(),0);await page.click('#quit');await page.locator('[data-choice]').first().waitFor();assert(await page.locator('#start').isHidden());assert.equal(await page.locator('[data-choice]:disabled').count(),0);
 const config={v:1,data:version,scope:'history',level:'hard',count:5,seed:42},url=origin+'#q='+Quiz.encode(config),deck=Quiz.questions(data,config);
 await page.goto(url);assert.equal(await page.locator('#copy,#copy-embed,#embed-code').count(),0);await page.click('#start');
 const question=n=>page.waitForFunction(n=>document.querySelector('.question-top')?.innerText.includes(`${n} / 5`),n);
 await page.click(`[data-id="${deck[0].answer.id}"]`);assert((await page.locator('#feedback').innerText()).includes('정답입니다!'));await page.click('#next');await question(2);
 await page.click('#hint');await page.click(`[data-id="${deck[1].answer.id}"]`);await page.click('#next');await question(3);
 const wrong=deck[2].options.find(p=>p.id!==deck[2].answer.id);await page.click(`[data-id="${wrong.id}"]`);assert((await page.locator('#feedback').innerText()).includes('아쉽지만'));await page.click('#next');await question(4);
 await page.click('#skip');await page.click('#next');await question(5);
 await page.click(`[data-id="${deck[4].answer.id}"]`);await page.click('#next');await page.locator('.score').waitFor();assert((await page.locator('.score').innerText()).includes('575 / 1000'));
 assert.equal(await page.locator('#retry').count(),0);assert((await page.locator('#app').innerText()).includes('정답률 60%'));await page.click('#copy-result');assert((await page.locator('#copy-status').innerText()).includes('2~20자'));await page.fill('#nickname','<script>');await page.click('#copy-result');assert.equal(await page.locator('#nickname').getAttribute('aria-invalid'),'true');await page.fill('#nickname','전주월드컵경기장');await page.click('#copy-result');const result=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(result.replace(/\r\n/g,'\n'),'닉네임: 전주월드컵경기장\n게임 종류: 선수 맞히기 · 전북 현대 · 역대\n난이도: 상\n문제 수: 5문제\n점수: 575 / 1000점');assert(!result.includes('http'));assert.equal(await page.locator('#nickname').getAttribute('aria-invalid'),null);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(Error('denied'))},configurable:true}));await page.click('#copy-result');assert(await page.locator('#copy-fallback').isVisible());
 await page.click('#home');assert.equal(new URL(page.url()).hash,'');assert(await page.locator('#start').isVisible());assert.equal(await page.locator('[data-choice]:disabled').count(),0);await page.locator('[data-choice=scope][data-value=jb]').click();assert.equal(new URL(page.url()).hash,'');await page.goto(origin);await page.locator('.option').first().waitFor();await page.click('#quit');await page.locator('[data-choice]').first().waitFor();assert(await page.locator('#start').isHidden());
 const choose=async(key,value)=>page.locator(`[data-choice="${key}"][data-value="${value}"]`).click();
 await choose('scope','jb');assert(await page.locator('#start').isHidden());await choose('level','normal');assert(await page.locator('#start').isHidden());await choose('count',5);assert(await page.locator('#start').isVisible());
 assert.equal(await page.locator('select').count(),0);
 for(const [scope,level,hints] of [['jb','easy',5],['history','normal',3],['k1','hard',1],['all','easy',5]]){
  await choose('scope',scope);await choose('level',level);await page.click('#start');assert.equal(await page.locator('#hints .hint').count(),hints);
  await page.click('#hint');page.once('dialog',d=>d.dismiss());await page.click('#quit');assert(await page.locator('#quit').isVisible());
  page.once('dialog',d=>d.accept());await page.click('#quit');assert(await page.locator('#start').isVisible());
 }
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'player_quiz/setup-mobile.png',fullPage:true});
 await page.goto(origin+'#q=broken');await page.getByText('게임을 열 수 없어요').waitFor();
 await page.setViewportSize({width:1440,height:1000});await page.goto(origin);await page.locator('.option').first().waitFor();await page.click('#quit');await page.locator('[data-choice]').first().waitFor();await page.screenshot({path:'player_quiz/landing-desktop.png',fullPage:true});
 const embedded=await context.newPage();await embedded.setContent(embed);await embedded.frameLocator('iframe').locator('.option').first().waitFor();assert.equal(await embedded.frameLocator('iframe').locator('.option').count(),4);await embedded.frameLocator('iframe').locator('#quit').click();await embedded.frameLocator('iframe').locator('[data-choice]').first().waitFor();assert(await embedded.frameLocator('iframe').locator('#start').isHidden());assert.equal(await embedded.frameLocator('iframe').locator('[data-choice]:disabled').count(),0);assert.equal(await embedded.frameLocator('iframe').locator('#copy-embed,#copy').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: admin configuration-free link/iframe; editable player settings and embed; button setup gate; all scopes/levels; quit; correct/wrong feedback and manual next; final 575/1000; result copy/fallback; desktop/mobile');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
