const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const Quiz=require('../engine.js');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const origin='http://127.0.0.1:8765/player_quiz/';
 const version=JSON.parse(fs.readFileSync('player_quiz/data/manifest.json','utf8')).version;
 const data=JSON.parse(fs.readFileSync(`player_quiz/data/${version}.json`,'utf8'));
 await page.goto(origin+'admin.html');await page.locator('#copy').waitFor();assert.equal(await page.locator('select,[data-choice],#generate').count(),0);
 const shareURL=await page.inputValue('#share-url'),embed=await page.inputValue('#embed-code');assert.equal(shareURL,origin);assert(!embed.includes('#q='));
 await page.click('#copy-embed');assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),embed);
 await page.click('#copy');assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),shareURL);
 await page.goto(shareURL);await page.locator('[data-choice]').first().waitFor();assert(await page.locator('#start').isHidden());assert.equal(await page.locator('[data-choice]:disabled').count(),0);
 const config={v:1,data:version,scope:'history',level:'hard',count:5,seed:42},url=origin+'#q='+Quiz.encode(config),deck=Quiz.questions(data,config);
 await page.goto(url);assert.equal(await page.locator('#copy,#copy-embed,#embed-code').count(),0);await page.click('#start');
 const question=n=>page.waitForFunction(n=>document.querySelector('.question-top')?.innerText.includes(`${n} / 5`),n);
 await page.click(`[data-id="${deck[0].answer.id}"]`);assert((await page.locator('#feedback').innerText()).includes('정답입니다!'));await page.waitForTimeout(800);assert((await page.locator('.question-top').innerText()).includes('1 / 5'));await question(2);assert.equal(await page.locator('#next').count(),0);
 await page.click('#hint');await page.click(`[data-id="${deck[1].answer.id}"]`);await question(3);
 const wrong=deck[2].options.find(p=>p.id!==deck[2].answer.id);await page.click(`[data-id="${wrong.id}"]`);
 assert((await page.locator('#feedback').innerText()).includes(deck[2].answer.name));assert.equal(await page.locator('.option:disabled').count(),4);
 await page.waitForTimeout(800);assert((await page.locator('.question-top').innerText()).includes('3 / 5'));await question(4);
 await page.getByRole('heading',{name:'시간 초과! 아쉽지만, 정답은…'}).waitFor({timeout:6500});
 assert((await page.locator('#feedback').innerText()).includes(deck[3].answer.name));await question(5);
 await page.click(`[data-id="${deck[4].answer.id}"]`);await page.locator('.score').waitFor();assert((await page.locator('.score').innerText()).includes('280 / 500'));
 await page.click('#copy-result');const result=await page.evaluate(()=>navigator.clipboard.readText());assert(result.includes('3/5')&&result.includes(url)&&result.includes('5초'));
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(Error('denied'))},configurable:true}));await page.click('#copy-result');assert(await page.locator('#copy-fallback').isVisible());
 await page.click('#home');assert(await page.locator('#start').isVisible());assert.equal(await page.locator('[data-choice]:disabled').count(),0);await page.locator('[data-choice=scope][data-value=jb]').click();assert.equal(new URL(page.url()).hash,'');await page.goto(origin);await page.locator('[data-choice]').first().waitFor();assert(await page.locator('#start').isHidden());
 const choose=async(key,value)=>page.locator(`[data-choice="${key}"][data-value="${value}"]`).click();
 await choose('scope','jb');assert(await page.locator('#start').isHidden());await choose('level','normal');assert(await page.locator('#start').isHidden());await choose('count',5);assert(await page.locator('#start').isVisible());
 assert.equal(await page.locator('select').count(),0);
 for(const [scope,level,hints] of [['jb','easy',5],['history','normal',3],['k1','hard',1],['all','easy',5]]){
  await choose('scope',scope);await choose('level',level);await page.click('#start');assert.equal(await page.locator('#hints .hint').count(),hints);
  page.once('dialog',d=>d.dismiss());await page.click('#quit');assert(await page.locator('#quit').isVisible());
  page.once('dialog',d=>d.accept());await page.click('#quit');assert(await page.locator('#start').isVisible());
 }
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'player_quiz/setup-mobile.png',fullPage:true});
 await page.goto(origin+'#q=broken');await page.getByText('게임을 열 수 없어요').waitFor();
 await page.setViewportSize({width:1440,height:1000});await page.goto(origin);await page.locator('[data-choice]').first().waitFor();await page.screenshot({path:'player_quiz/landing-desktop.png',fullPage:true});
 const embedded=await context.newPage();await embedded.setContent(embed);await embedded.frameLocator('iframe').locator('[data-choice]').first().waitFor();assert(await embedded.frameLocator('iframe').locator('#start').isHidden());assert.equal(await embedded.frameLocator('iframe').locator('[data-choice]:disabled').count(),0);assert.equal(await embedded.frameLocator('iframe').locator('#copy-embed,#copy').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: admin configuration-free link/iframe; editable player settings and embed; button setup gate; all scopes/levels; quit; correct reveal then auto; wrong/timeout reveal then auto; final 280/500; result copy/fallback; desktop/mobile');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
