'use strict';
const app=document.querySelector('#app');let picks=[],busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shirt=role=>`<svg class="shirt" viewBox="0 0 200 220" aria-hidden="true"><path d="M62 20 20 44 3 91 40 107 50 85v121h100V85l10 22 37-16-17-47-42-24-18 17H80Z" fill="currentColor"/><path d="M80 20q20 26 40 0M65 40v164M135 40v164" fill="none" stroke="#cdf775" stroke-width="9"/><text x="100" y="126" text-anchor="middle" fill="#eff8da" font-size="32" font-family="sans-serif" font-weight="900">${role}</text></svg>`;
function card(c,i){return `<button class="pick ${c.player?'player-card':'decision-card'}" data-pick="${c.id}" aria-label="${esc(c.title)} 선택"><div class="card-art"><span class="card-number">0${i+1}</span>${c.player?shirt(c.role)+`<img src="${esc(c.player.photo)}" alt="" referrerpolicy="no-referrer">`:`<span class="decision-icon">${c.icon}</span>`}<span class="art-caption">${c.player?'전성기 영입 · 가상 시나리오':esc(c.note)}</span></div><div class="card-copy"><div class="card-title"><h2>${esc(c.title)}</h2><span class="pick-arrow" aria-hidden="true">↗</span></div><p>${esc(c.description)}</p><span class="pick-label">${c.player?'이 선수 영입하기':'이렇게 결정하기'} <span>→</span></span></div></button>`;}
function header(){return `<header><a href="./" class="brand">JEONBUK <b>DIRECTOR</b></a><span class="edition">팬이 만드는 가상의 전북</span></header>`;}
function footer(){return `<footer><details><summary>이 게임은 어떻게 만들어졌나요?</summary><p>실제 전북에서 뛴 선수와 가상의 영입·운영 상황을 결합한 팬 게임입니다. 전성기 영입은 상상 속 조건이며 현재 이적 가능성이나 선수의 능력치를 평가하지 않습니다. 유스 후보는 가상의 육성 방향입니다.</p><p>공격·중원·수비 선택 횟수로 성향을 요약하며, 동률이면 균형형으로 표시합니다. 우승 확률이나 경기 결과를 예측하지 않습니다. 닉네임과 선택 기록은 서버에 저장하지 않습니다.</p><div class="sources">${Object.values(DirectorPlayers).map(p=>`<a href="${p.source}" target="_blank" rel="noopener">${p.name} 기록 ↗</a>`).join('')}</div></details></footer>`;}
function render(){busy=false;document.body.dataset.screen='play';const q=Director.round(picks),selected=Director.resolve(picks);app.innerHTML=`${header()}<section class="intro"><div class="round-label"><span class="live-dot"></span>전북 단장 체험 <span class="round-count">${picks.length+1} / 5 · ${q.label}</span></div><h1>${q.title.split('\n').map(esc).join('<br>')}</h1><p>${esc(q.description)}</p></section><div class="step-track" aria-label="${picks.length+1}번째 선택">${[0,1,2,3,4].map(n=>`<i class="${n<=picks.length?'active':''}"></i>`).join('')}</div><section class="cards" aria-label="${q.label}">${q.choices.map(card).join('')}</section><section class="desk"><div><span class="desk-label">단장 노트</span><p>${selected.length?selected.map(c=>`<span>${esc(c.title)}</span>`).join(''):'정답은 없습니다. 당신의 취향이 곧 영입 기준입니다.'}</p></div>${picks.length?'<button class="text-button" id="back">← 이전 선택</button>':'<span class="five-picks">딱 5번 고르면 완성</span>'}</section>${footer()}`;
app.querySelectorAll('img').forEach(img=>{img.onload=()=>img.parentElement.classList.add('photo-ready');img.onerror=()=>img.remove();if(img.complete&&img.naturalWidth)img.onload();});app.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{if(busy)return;busy=true;picks.push(b.dataset.pick);if(picks.length===5)finish();else render();window.scrollTo(0,0);app.querySelector('h1').setAttribute('tabindex','-1');app.querySelector('h1').focus({preventScroll:true});});if(picks.length)app.querySelector('#back').onclick=()=>{picks.pop();render();};}
function finish(){document.body.dataset.screen='result';const r=Director.result(picks);app.innerHTML=`${header()}<section class="result-heading"><p class="eyebrow">YOUR JEONBUK · 계약 완료</p><h1>${r.title}</h1><p>${r.comment}</p></section><section class="report"><div class="report-head"><span>단장 보고서</span><span>5 DECISIONS / MY CLUB</span></div><div class="squad"><div class="pitch-circle"></div><span class="pitch-label">나의 영입 명단</span>${r.signings.map(c=>`<div class="signing">${shirt(c.role)}<strong>${c.title}</strong><small>전성기 영입</small></div>`).join('')}</div><div class="report-body"><div class="tallies">${[['attack','공격'],['creative','중원'],['defense','수비']].map(([key,label])=>`<div><strong>${r.counts[key]}<small>회</small></strong><span>${label} 선택</span></div>`).join('')}</div><p class="tally-note">운영 조건 1회를 제외한 4번의 선택을 요약했어요.</p><dl>${r.selected.slice(1).map((c,i)=>`<div><dt>${['받아들인 조건','영입·육성·훈련','팀의 색깔','결승 80분'][i]}</dt><dd>${c.title}</dd></div>`).join('')}</dl></div></section><section class="share-panel"><h2>이 전북, 우승 가능?</h2><p>당신의 선택을 댓글로 올리고 다른 팬의 생각을 들어보세요.</p><div class="share-actions"><input id="nickname" maxlength="20" placeholder="닉네임 (선택)" aria-label="결과에 넣을 닉네임"><button class="primary" id="copy">내 단장 보고서 복사 ↗</button></div><p id="copy-status" role="status"></p><textarea id="copy-fallback" aria-label="직접 복사할 결과" readonly hidden></textarea><button class="text-button" id="restart">다른 선택으로 새로 해보기 →</button></section>${footer()}`;app.querySelector('#copy').onclick=copy;app.querySelector('#nickname').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing)copy();};app.querySelector('#restart').onclick=()=>{picks=[];render();window.scrollTo(0,0);};}
async function copy(){const field=app.querySelector('#nickname'),name=field.value.normalize('NFC').trim();if(name&&(!/^[가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9 _-]{1,20}$/.test(name))){app.querySelector('#copy-status').textContent='닉네임은 한글·영문·숫자·공백·밑줄·하이픈 20자 이내로 입력해 주세요.';field.focus();return;}const text=Director.share(picks,name),fallback=app.querySelector('#copy-fallback');fallback.hidden=true;try{await navigator.clipboard.writeText(text);app.querySelector('#copy-status').textContent='복사 완료! 댓글에 붙여넣어 주세요.';}catch{fallback.value=text;fallback.hidden=false;fallback.focus();fallback.select();app.querySelector('#copy-status').textContent='자동 복사가 차단되어 내용을 선택했어요. 직접 복사해 주세요.';}}
render();
