'use strict';
const app=document.querySelector('#app');let topicId=null,answers=[],index=0,orders=[],busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(options){const out=[...options];for(let i=out.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[out[i],out[j]]=[out[j],out[i]];}return out;}
function header(){return '<header><button class="brand" id="topics">JEONBUK <b>FOOTBALL NOTES</b></button><span>축구를 좋아하는 나를 읽다</span></header>';}
function footer(){return '<footer><details><summary>결과 해석과 개인정보 안내</summary><p>축구 상황에 대한 선택을 네 가지 관점으로 묶은 창작 테스트입니다. 각 답은 주 관점과 보조 관점에 반영됩니다. 각 문항의 선택지 평균을 기준으로 답을 합산하고, 관점별로 가능한 양쪽 범위를 따로 반영해 방향을 읽습니다. 중간에 가까우면 혼합으로 표시하며, 같은 강도의 관점은 문항 설계 순서로 대표 이름을 정합니다. 대표 이름보다 네 관점과 실제 답변을 함께 읽어 주세요.</p><p>검증된 심리검사, 성격 진단, 전문가의 평가가 아닙니다. 팬심의 크기나 능력의 우열을 재지 않습니다. 결과는 오늘 고른 답에 대한 재미용 해석입니다. 답변·닉네임은 서버나 브라우저 저장소에 저장하지 않으며 새로고침하면 초기화됩니다.</p></details></footer>';}
function bindHeader(){app.querySelector('#topics').onclick=()=>{if(busy)return;if(document.body.dataset.screen==='question'&&answers.length&&!confirm('주제를 바꾸면 지금 답변은 초기화됩니다. 주제 선택으로 갈까요?'))return;landing();};}
function focusTitle(){window.scrollTo(0,0);app.querySelector('h1').focus({preventScroll:true});}
function landing(){topicId=null;answers=[];index=0;busy=false;document.body.dataset.screen='landing';app.innerHTML=`${header()}<section class="lobby"><p class="eyebrow">THE WAY YOU LOVE FOOTBALL</p><h1 tabindex="-1">같은 축구를 좋아해도,<br><em>우리는 조금 다르니까.</em></h1><p class="lobby-note">어려운 건 정답이 아니라, 하나만 고르는 일.<br>지금 궁금한 나를 골라보세요.</p><div class="topic-list">${Object.entries(FootballTest.topics).map(([id,t])=>`<button class="topic-card" data-topic="${id}"><span class="topic-no">${t.icon}</span><span class="topic-copy"><small>${t.kicker}</small><strong>${t.name}</strong><span>${t.intro}</span><i>${t.scene} · 20문항</i></span><span class="topic-arrow" aria-hidden="true">↗</span></button>`).join('')}</div><p class="lobby-foot">정답·점수·시간 제한 없이. 이전 질문으로 돌아가 답을 바꿀 수 있어요.</p></section>${footer()}`;bindHeader();app.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>start(b.dataset.topic));}
function start(id){const t=FootballTest.topic(id);topicId=id;answers=[];index=0;orders=t.questions.map(q=>shuffle(q.options));render();focusTitle();}
function render(){busy=false;document.body.dataset.screen='question';const t=FootballTest.topic(topicId),q=t.questions[index];app.innerHTML=`${header()}<section class="question"><div class="question-meta"><span>${t.name}</span><span class="counter" aria-label="${index+1}번째, 총 ${t.questions.length}문항">${index+1}<small> / ${t.questions.length}</small></span></div><div class="progress" role="progressbar" aria-label="답변한 문항 수" aria-valuemin="0" aria-valuemax="${t.questions.length}" aria-valuenow="${answers.length}"><i style="width:${answers.length/t.questions.length*100}%"></i></div><p class="scene-label">SCENE ${String(index+1).padStart(2,'0')}</p><h1 tabindex="-1">${q.title.split('\n').map(esc).join('<br>')}</h1><p class="context">${esc(q.context)}</p><div class="choices" role="group" aria-label="응답 선택">${orders[index].map((a,n)=>`<button data-answer="${a.id}" class="${answers[index]===a.id?'selected':''}" aria-pressed="${answers[index]===a.id}"><span class="letter">${String.fromCharCode(65+n)}</span><span>${esc(a.text)}</span><span class="choice-mark" aria-hidden="true">${answers[index]===a.id?'✓':'↗'}</span></button>`).join('')}</div><div class="navigation"><button id="back" ${index===0?'disabled':''}>← 이전 응답</button><span>${answers[index]?'선택했던 답입니다. 바꾸거나 다음으로 이동하세요.':'조금 더 마음이 가는 쪽을 골라 주세요.'}</span><button id="next" ${answers[index]?'':'hidden'}>${index===t.questions.length-1?'결과 보기':'다음 →'}</button></div></section>${footer()}`;bindHeader();app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(busy)return;busy=true;answers[index]=b.dataset.answer;app.querySelectorAll('[data-answer]').forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b);});setTimeout(advance,120);});app.querySelector('#back').onclick=()=>{if(busy||index===0)return;index--;render();focusTitle();};app.querySelector('#next').onclick=()=>{if(!busy)advance();};}
function advance(){const total=FootballTest.topic(topicId).questions.length;if(index===total-1)finish();else{index++;render();}focusTitle();}
function finish(){busy=false;document.body.dataset.screen='result';const t=FootballTest.topic(topicId),r=FootballTest.result(topicId,answers);app.innerHTML=`${header()}<section class="result-hero"><p class="eyebrow">${t.kicker} · 20개의 선택</p><p class="result-pre">이번 답변에서 만난 당신은</p><h1 tabindex="-1">${r.title}</h1><p class="result-summary">${r.summary}</p><div class="result-tags">${r.dimensions.map(d=>`<span>${d.label}</span>`).join('')}</div></section><p class="interpretation">${r.intro}</p><section class="dimension-list" aria-label="네 관점의 상세 해석">${r.dimensions.map((d,i)=>`<article class="dimension"><div class="dimension-head"><span>0${i+1}</span><h2>${d.name}</h2><small>${d.side==='mixed'?'두 방향이 함께 나타남':Math.abs(d.value)>=.5?'이쪽 선택이 비교적 뚜렷함':'이쪽 선택에 조금 가까움'}</small></div><div class="spectrum" aria-label="${d.label}"><span>${d.low}</span><span>${d.high}</span><div><i style="left:${Math.max(2,Math.min(98,(d.value+1)*50))}%"></i></div></div><h3>${d.label}</h3><p>${d.read}</p><div class="evidence"><h4>이 해석에 연결된 실제 답변</h4>${d.evidence.map(e=>`<blockquote><span>${e.index+1}번 · ${esc(e.title)}</span><p>“${esc(e.text)}”</p></blockquote>`).join('')}</div>${d.counter?`<p class="counter-note"><strong>다른 방향도 있었어요.</strong> ${d.counter.index+1}번에서는 “${esc(d.counter.text)}”를 골랐습니다. 이 장면에서는 다른 조건을 더 중요하게 본 답이 함께 있습니다.</p>`:''}<div class="tradeoff"><h4>이 취향과 함께 살펴볼 대가</h4><p>${d.cost}</p></div></article>`).join('')}</section><section class="closing"><div><h2>다른 취향과 만났을 때</h2><p>${r.conversation}</p></div><div><h2>다음에 해볼 작은 실험</h2><p>${r.experiment}</p></div></section><section class="share-panel"><h2>내 결과를 댓글로 남겨볼까요?</h2><p>닉네임은 선택 사항입니다. 복사 내용에 게임 링크는 넣지 않습니다.</p><div class="share-actions"><input id="nickname" maxlength="20" placeholder="닉네임 (선택)" aria-label="결과에 넣을 닉네임"><button class="primary" id="copy">결과 요약 복사 ↗</button></div><p id="copy-status" role="status"></p><textarea id="copy-fallback" readonly aria-label="직접 복사할 결과" hidden></textarea><div class="result-actions"><button id="revise">← 답변 돌아보기</button><button id="choose-topic">다른 주제 해보기 →</button></div></section><details class="answer-review"><summary>내가 고른 20개 답 · 눌러서 수정</summary>${t.questions.map((q,i)=>`<button data-revise="${i}"><span>${i+1}. ${q.title.replace('\n',' ')}</span><small>${esc(q.options.find(a=>a.id===answers[i]).text)}</small></button>`).join('')}</details><p class="disclaimer">의학적·심리학적 진단이 아닌, 오늘의 축구 선택에 대한 재미용 해석입니다.</p>${footer()}`;bindHeader();app.querySelector('#copy').onclick=copy;app.querySelector('#nickname').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing)copy();};app.querySelector('#revise').onclick=()=>revise(19);app.querySelectorAll('[data-revise]').forEach(b=>b.onclick=()=>revise(Number(b.dataset.revise)));app.querySelector('#choose-topic').onclick=()=>{landing();focusTitle();};}
function revise(i){index=i;render();focusTitle();}
async function copy(){const input=app.querySelector('#nickname'),name=input.value.normalize('NFC').trim(),status=app.querySelector('#copy-status');if(name&&!/^[가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9 _-]{1,20}$/.test(name)){status.textContent='닉네임은 한글·영문·숫자·공백·밑줄·하이픈 20자 이내로 입력해 주세요.';input.focus();return;}const text=FootballTest.share(topicId,answers,name),fallback=app.querySelector('#copy-fallback');fallback.hidden=true;try{await navigator.clipboard.writeText(text);status.textContent='복사했어요. 댓글에 붙여넣어 주세요.';}catch{fallback.value=text;fallback.hidden=false;fallback.focus();fallback.select();status.textContent='자동 복사가 차단되어 내용을 선택했어요. 직접 복사해 주세요.';}}
landing();
