(function(root){
'use strict';
const topics=typeof module!=='undefined'?require('./topics.js'):root.FootballTopics;
const names={manager:[['지금의 기회를 붙잡는 단장','다음 시즌까지 설계하는 단장'],['현장의 맥락을 듣는 단장','선택의 기준을 세우는 단장'],['팀의 색을 선명하게 만드는 단장','변화에 대비하는 단장'],['함께한 시간을 지키는 단장','다음 역할을 다시 짜는 단장']],fan:[['나만의 장면을 간직하는 팬','함께한 시간을 모으는 팬'],['익숙함을 깊게 즐기는 팬','처음의 설렘을 찾는 팬'],['마음이 먼저 움직이는 팬','장면을 다시 읽는 팬'],['오래 좋아할 리듬을 지키는 팬','그날의 순간에 뛰어드는 팬']],football:[['공간이 열리는 순간을 좋아하는 관객','기회를 빚는 과정을 좋아하는 관객'],['위험을 닫는 수비를 즐기는 관객','앞에서 빼앗는 축구를 즐기는 관객'],['함께 맞아떨어지는 장면을 좋아하는 관객','예상 밖 해법을 기다리는 관객'],['조이고 푸는 호흡을 즐기는 관객','끊이지 않는 흐름에 끌리는 관객']]};
const intros={manager:'이 결과는 누가 더 유능한 단장인지 평가하지 않습니다. 같은 자원으로도 어떤 비용을 먼저 감수하는지, 무엇을 끝까지 남기려 하는지를 읽습니다.',fan:'이 결과는 팬심이 얼마나 큰지 재지 않습니다. 축구가 당신의 하루에서 어떤 자리를 차지하고, 무엇을 오래 기억하게 하는지에 대한 해석입니다.',football:'이 결과는 어떤 전술이 더 우수한지 판정하지 않습니다. 같은 결과가 나더라도 어떤 과정과 위험을 더 기꺼이 지켜보는지에 대한 취향입니다.'};
const experiments={manager:[['단기 영입 하나를 정할 때, 다음 시즌 그 자리를 다시 채우는 비용까지 한 줄로 써보세요.','장기 계획마다 이번 시즌 팬과 선수에게 돌려줄 중간 성과 하나를 정해보세요.'],['현장에서 좋다고 느낀 선수와 같은 역할의 다른 후보를 공통 항목 세 개로 비교해보세요.','자료로 후보를 고른 뒤, 그 자료가 놓칠 수 있는 팀 안의 역할을 현장에 물어보세요.'],['핵심 선수가 빠지는 한 가지 상황만 가정하고 실제로 쓸 대안을 적어보세요.','남겨둔 대안마다 유지 비용을 적고, 쓰일 가능성이 낮은 하나를 덜어내보세요.'],['현재 관계를 지키는 선택이 새로 합류할 선수에게도 같은 기준으로 설명되는지 물어보세요.','재편 대상에게 조건만 전달하지 말고, 과거 기여와 다음 역할을 구분해서 설명해보세요.']],fan:[['오늘 혼자 기억하고 싶은 장면 하나를 동행에게도 짧게 들려줘 보세요.','다음 직관에는 동행의 감상 전에 나에게 남은 순간 한 줄을 먼저 적어보세요.'],['익숙한 관람 루틴은 지키되, 가는 길 하나만 바꿔보세요.','새로운 경험 뒤에 다음에도 반복하고 싶은 작은 루틴 하나를 남겨보세요.'],['경기 직후 감상을 저장해 두었다가 다음 날 달라진 부분을 한 줄 덧붙여보세요.','분석이 끝나기 전이라도 지금의 감정 한 단어만 친구에게 전해보세요.'],['일상에 무리가 없는 범위에서 한 번은 꼭 현장에서 보고 싶은 장면을 미리 골라보세요.','다음 특별한 경기 전에 귀가 시간과 다음 날 쉴 시간을 먼저 확보해보세요.']],football:[['다음 경기에서 전진하지 않은 패스가 이후 공간을 만든 장면을 하나 찾아보세요.','공을 더 돌리는 사이 사라진 전진 기회가 있었는지도 같이 봐보세요.'],['수비 위치를 지킨 덕분에 막은 공간과, 상대에게 준 시간을 함께 기록해보세요.','압박 성공 장면뿐 아니라 한 번 깨졌을 때 누가 어떤 공간을 책임졌는지 따라가 보세요.'],['약속된 패턴에서 한 선수가 다르게 판단한 순간을 하나 골라 결과와 과정을 나눠보세요.','멋진 개인 선택 직전에 동료들이 만들어준 위치와 움직임도 함께 찾아보세요.'],['속도를 늦춘 뒤 우리 팀뿐 아니라 상대도 얻은 준비 시간을 살펴보세요.','흐름을 이어간 5분 뒤에 선수들의 간격과 선택이 어떻게 달라졌는지 봐보세요.']]};
function topic(id){if(!Object.hasOwn(topics,id))throw Error('테스트 주제를 확인해 주세요.');return topics[id];}
function resolve(id,answers,complete=false){const t=topic(id);if(!Array.isArray(answers)||answers.length>t.questions.length||(complete&&answers.length!==t.questions.length))throw Error('모든 문항에 답해 주세요.');return Array.from({length:answers.length},(_,i)=>{const a=t.questions[i].options.find(a=>a.id===answers[i]);if(!a)throw Error('응답 기록을 확인해 주세요.');return a;});}
function result(id,answers){const t=topic(id),selected=resolve(id,answers,true);const dimensions=t.axes.map((a,index)=>{let raw=0,baseline=0,minimum=0,maximum=0;selected.forEach(s=>raw+=s.weights[index]||0);t.questions.forEach(q=>{const values=q.options.map(s=>s.weights[index]||0);baseline+=values.reduce((a,b)=>a+b,0)/values.length;minimum+=Math.min(...values);maximum+=Math.max(...values);});const centered=raw-baseline,value=centered>=0?centered/(maximum-baseline):centered/(baseline-minimum),side=Math.abs(value)<0.18?'mixed':value>0?'high':'low';const evidence=selected.map((s,i)=>({index:i,title:t.questions[i].title.replace('\n',' '),text:s.text,weight:(s.weights[index]||0)-t.questions[i].options.reduce((sum,a)=>sum+(a.weights[index]||0),0)/t.questions[i].options.length,primary:t.questions[i].axis===index})).filter(e=>e.weight!==0).sort((a,b)=>Number(b.primary)-Number(a.primary)||Math.abs(b.weight)-Math.abs(a.weight)||a.index-b.index);const matching=evidence.filter(e=>side==='mixed'||(side==='high'?e.weight>0:e.weight<0));const other=evidence.find(e=>side==='high'?e.weight<0:side==='low'?e.weight>0:false);return {...a,index,raw,value,side,label:side==='mixed'?`${a.low} ↔ ${a.high}`:side==='high'?a.high:a.low,read:side==='mixed'?`이번 답에서는 '${a.low}'와 '${a.high}' 중 한쪽으로만 모이지 않았습니다. 상황에서 얻는 것과 잃는 것을 달리 보았을 가능성이 있습니다. 이것만으로 결정력이 부족하거나 항상 균형적이라고 말할 수는 없습니다.`:side==='high'?a.highRead:a.lowRead,cost:side==='mixed'?'상황마다 기준을 바꾸는 선택은 유연할 수 있습니다. 다만 무엇 때문에 기준이 달라졌는지 말로 남겨두면 다음 선택을 설명하기 쉬워집니다.':side==='high'?a.highCost:a.lowCost,evidence:matching.slice(0,2),counter:other||null};});const ranked=[...dimensions].sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)||a.index-b.index),lead=ranked[0],second=ranked[1];const title=lead.side==='mixed'?`상황에 따라 기준을 바꾸는 ${t.short}`:names[id][lead.index][lead.side==='high'?1:0];const supporting=second.side==='mixed'?`다른 관점에서는 한 방향으로 모이지 않은 답도 함께 나타났습니다.`:`여기에 '${second.label}' 쪽 선택도 겹쳐 있습니다. 같은 유형 이름이 나와도 이 두 번째 관점과 각 문항의 답은 달라질 수 있습니다.`;return {topic:id,title,intro:intros[id],dimensions,lead:lead.index,summary:`이번 20개 답에서 가장 두드러진 관점은 '${lead.label}'입니다. ${supporting}`,experiment:lead.side==='mixed'?`고르기 가장 어려웠던 문항 하나를 다시 보고, 상황의 어떤 조건이 바뀌면 다른 답을 고를지 적어보세요.`:experiments[id][lead.index][lead.side==='high'?1:0],conversation:lead.side==='mixed'?`친구와 같은 질문을 하나 고르고, 답보다 그 답을 고른 조건을 비교해 보세요.`:`'${lead.label}'과 다른 쪽을 고른 사람에게는 '${lead.side==='high'?lead.low:lead.high}'이 지키려는 가치도 있습니다. 어느 쪽이 옳은지 묻기 전에 서로 감수하기 어려운 비용부터 이야기해 보세요.`};}
function share(id,answers,name=''){const r=result(id,answers);return `🌿 ${topic(id).name}${name?' · '+name:''}\n${r.title}\n${r.dimensions.map(d=>d.name+': '+d.label).join('\n')}\n20문항 선택 해석 · 재미용 축구 취향 테스트`;}
const api={topics,topic,resolve,result,share};if(typeof module!=='undefined')module.exports=api;else root.FootballTest=api;
})(globalThis);
