(function(root){
'use strict';
const players=typeof module!=='undefined'?require('./players.js'):root.DirectorPlayers;
const option=(id,title,description,trait,extra={})=>({id,title,description,trait,...extra});
const player=(id,description,trait,role)=>option(id,players[id].name,description,trait,{player:players[id],role});
function round(picks){const step=picks.length;if(step===0)return {label:'드림 영입',title:'전성기 딱 한 명.\n누구를 데려올까요?',description:'당신이 전북 단장이라면? 카드 한 장을 눌러 영입하세요.',choices:[player('19980443','골문 앞 해결사에게 맡긴다','attack','ST'),player('20030114','창의적인 공격에 승부를 건다','creative','AM'),player('20120270','측면에서 판을 흔든다','attack','LW')]};
if(step===1)return {label:'계약의 조건',title:`${players[picks[0]].name} 영입 완료.\n대신 조건이 있습니다.`,description:'가상의 영입 예산이 빠듯합니다. 어떤 조건을 받아들일까요?',choices:[option('domestic','다음 영입은 국내 선수','외국인 추가 영입을 접고, 검증된 전북 출신을 찾는다','balance',{icon:'KR',note:'다음: 국내 선수 3명'}),option('academy','마지막 한 자리는 유스','추가 이적료 대신 유망주에게 기회를 준다','youth',{icon:'U21',note:'다음: 유스 육성 방향'}),option('keep','영입은 여기까지','기존 선수단을 믿고, 남은 자원을 훈련에 쓴다','trust',{icon:'ONE',note:'다음: 팀 집중 훈련'})]};
if(step===2){if(picks[1]==='domestic')return {label:'마지막 영입',title:'빈자리 하나.\n누구로 채울까요?',description:'약속대로 국내 선수 중 한 명만 추가 영입합니다.',choices:[player('20160004','중원에서 공격의 실마리를 찾는다','creative','AM'),player('20060011','수비의 끈기와 팀의 중심을 세운다','defense','DF'),player('20060014','마지막 골문부터 든든하게 만든다','defense','GK')]};
if(picks[1]==='academy')return {label:'유스 프로젝트',title:'당신이 키울\n다음 주인공은?',description:'실제 선수가 아닌 가상의 유스 육성 계획입니다.',choices:[option('young-fw','유스 공격수','실수해도 기회는 계속. 골을 넣는 경험을 쌓게 한다','attack',{icon:'FW',note:'유스 프로젝트 · 공격'}),option('young-mf','유스 미드필더','중원의 미래에게 공을 맡긴다','creative',{icon:'MF',note:'유스 프로젝트 · 중원'}),option('young-df','유스 수비수','한 시즌을 함께 버틸 수비 자원을 키운다','defense',{icon:'DF',note:'유스 프로젝트 · 수비'})]};
return {label:'기존 선수단 강화',title:'새 영입 대신,\n우리 팀의 무기를 만듭니다.',description:'추가 영입 없이 선택한 분야에 훈련을 집중합니다.',choices:[option('train-finish','결정력 훈련','만든 기회를 골로 바꾸는 데 집중한다','attack',{icon:'GOAL',note:'집중 훈련 · 마무리'}),option('train-pass','패스와 연계','서로의 움직임을 더 잘 이해하게 만든다','creative',{icon:'PASS',note:'집중 훈련 · 연계'}),option('train-defense','수비 조직력','같이 움직이고, 같이 막는 팀을 만든다','defense',{icon:'BLOCK',note:'집중 훈련 · 수비'})]};}
if(step===3)return {label:'팀의 색깔',title:'이 전북은\n어떤 축구를 합니까?',description:'당신이 영입한 선수들과 함께할 운영 방향을 정하세요.',choices:[option('press','먼저 몰아붙인다','높이 압박하고, 공을 뺏으면 바로 전진','attack',{icon:'↑↑',note:'방향 · 전방 압박'}),option('possession','공으로 지배한다','서두르지 않고 패스로 기회를 만든다','creative',{icon:'↔',note:'방향 · 점유와 연계'}),option('counter','단단하게, 한 번에','수비 간격을 지키고 역습을 노린다','defense',{icon:'↗',note:'방향 · 수비 후 역습'})]};
if(step===4)return {label:'마지막 결단',title:'결승 후반 80분.\n0 : 0, 당신의 선택은?',description:'가상의 경기입니다. 감독과 마지막 운영 방향을 결정하세요.',choices:[option('all-in','공격수 한 명 더!','연장 전에 끝내자. 공격에 무게를 싣는다','attack',{icon:'+FW',note:'결단 · 공격 강화'}),option('fresh','중원에 새 에너지','지친 중원을 바꿔 흐름을 되찾는다','creative',{icon:'+MF',note:'결단 · 중원 교체'}),option('extra-time','연장까지 준비한다','수비부터 정비하고 긴 승부를 준비한다','defense',{icon:'120′',note:'결단 · 안정 우선'})]};
return null;}
function resolve(picks){if(!Array.isArray(picks)||picks.length>5)throw Error('선택 기록이 올바르지 않습니다.');const selected=[];for(let i=0;i<picks.length;i++){const choice=round(picks.slice(0,i)).choices.find(c=>c.id===picks[i]);if(!choice)throw Error('이 단계에서 선택할 수 없습니다.');selected.push(choice);}return selected;}
function result(picks){const selected=resolve(picks);if(selected.length!==5)throw Error('다섯 번의 선택을 완료해 주세요.');const counts={attack:0,creative:0,defense:0};selected.forEach(c=>{if(c.trait in counts)counts[c.trait]++;});const max=Math.max(...Object.values(counts)),leaders=Object.keys(counts).filter(k=>counts[k]===max);let key=leaders.length===1?leaders[0]:'balance';const titles={attack:'공격에 진심인 단장',creative:'중원을 설계하는 단장',defense:'쉽게 무너지지 않는 단장',balance:'균형을 고민하는 단장'};const comments={attack:'골이 필요한 순간, 당신은 한 발 더 앞으로 나갔습니다.',creative:'당신은 경기를 풀어갈 패스와 연결에 힘을 실었습니다.',defense:'당신은 마지막 순간까지 버틸 팀의 뼈대를 먼저 세웠습니다.',balance:'한 가지 방식에 올인하기보다 서로 다른 장점을 골랐습니다.'};return {title:titles[key],comment:comments[key],selected,counts,signings:selected.filter(c=>c.player),policy:selected[1].title};}
function share(picks,name=''){const r=result(picks);return `⚽ 나의 전북 단장 보고서${name?' · '+name:''}\n${r.title}\n영입: ${r.signings.map(c=>c.title).join(' · ')}\n조건: ${r.policy}\n${picks[1]==='domestic'?'보강':'육성·훈련'}: ${r.selected[2].title}\n전술: ${r.selected[3].title}\n결승 80분: ${r.selected[4].title}\n이 전북, 여러분이라면 어떻게 바꾸실 건가요?`;}
const api={round,resolve,result,share};if(typeof module!=='undefined')module.exports=api;else root.Director=api;
})(globalThis);
