'use strict';
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config,data,deck,index=0,extra=0,locked=false,results=[],shared=false,chosen={scope:false,level:false,count:false};
let playerName='',quickEntry=false;
let advanceId=null;
function stopTimer(){if(advanceId!==null)clearTimeout(advanceId);advanceId=null;}
const safePhoto=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:'';}catch{return '';}};
async function getJSON(url){const r=await fetch(url);if(!r.ok)throw Error('출제 데이터를 불러오지 못했습니다. 잠시 후 새로고침해 주세요.');return r.json();}
function displayedScore(raw){return Quiz.score100(raw,config.count,config.level);}
function subtitle(){return `${Quiz.scopes[config.scope]} · 난이도 ${Quiz.levels[config.level].name} · ${config.count}문제 · 시간 제한 없음`;}
function setupReady(){return Object.values(chosen).every(Boolean);}
const scopeCards={jb:['전북 현대','지금의 녹색 전사들','CURRENT SQUAD','shield'],history:['역대 전북','추억 속 레전드까지','ALL-TIME JEONBUK','star'],k1:['K리그1','1부 리그를 누비는 선수들','K LEAGUE 1','ball'],all:['K리그1 + K리그2','두 리그를 아우르는 축구력','ALL LEAGUES','pitch']};
const icons={shield:'<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6Z"/><path d="m8 12 3 3 5-6"/>',star:'<path d="m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',ball:'<circle cx="12" cy="12" r="9"/><path d="m12 7 5 4-2 6H9l-2-6Z M12 3v4m9 4-4 0m-2 6 3 3M9 17l-3 3M7 11l-4 0"/>',pitch:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16M3 9h4v6H3m18-6h-4v6h4"/><circle cx="12" cy="12" r="3"/>'};
function choiceContent(key,value){
 if(key==='scope'){const [name,desc,kicker,icon]=scopeCards[value];return `<span class="card-top"><span class="scope-symbol"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${icons[icon]}</svg></span><span class="card-kicker">${kicker}</span></span><strong class="card-title">${name}</strong><span class="card-description">${desc}</span><span class="card-foot">${Quiz.pool(data,value).length}명의 선수 <span aria-hidden="true">↗</span></span>`;}
 if(key==='level'){const l=Quiz.levels[value],descs={easy:'가볍게 몸풀기',normal:'팬심을 시험하기',hard:'진짜 고수라면'};return `<span class="difficulty-name">${l.name}<span>난이도</span></span><span class="hint-dots" aria-hidden="true">${[1,2,3,4,5].map(n=>`<i class="${n<=l.hints?'lit':''}"></i>`).join('')}</span><strong class="level-description">${descs[value]}</strong><span class="card-description">처음부터 힌트 ${l.hints}개</span>`;}
 const descs={5:'워밍업',10:'한 판 승부',20:'풀타임 도전'};return `<span class="count-number">${String(value).padStart(2,'0')}<small>문제</small></span><span class="card-description">${descs[value]}</span>`;
}
function choiceGroup(key,number,title,subtitle,values){return `<section class="choice-group group-${key}" role="group" aria-label="${esc(title)}"><div class="group-heading"><span class="step-number">${number}</span><span>${title}<small>${subtitle}</small></span>${chosen[key]?'<span class="step-done">선택 완료 ✓</span>':''}</div><div class="choice-options ${key==='scope'?'scope-options':''}">${values.map(value=>{const active=chosen[key]&&String(config[key])===String(value);return `<button type="button" class="choice${active?' selected':''}" data-choice="${key}" data-value="${value}" aria-pressed="${active}"><span class="choice-check" aria-hidden="true">${active?'✓':''}</span>${choiceContent(key,value)}</button>`;}).join('')}</div></section>`;}
function setupControls(){const count=Object.values(chosen).filter(Boolean).length;return `<section class="setup lobby-setup"><div class="setup-heading"><p class="eyebrow">MATCH SETUP</p><span class="setup-counter">${count}<span> / 3</span></span></div>${choiceGroup('scope','01','선수 범위','내가 아는 선수들이 있는 무대를 선택하세요.',Object.keys(Quiz.scopes))}${choiceGroup('level','02','난이도','공개할 기본 힌트 수를 선택하세요.',Object.keys(Quiz.levels))}${choiceGroup('count','03','문제 수','원하는 길이로 한 판 즐겨보세요.',[5,10,20])}<div class="start-zone"><p id="setup-status">${setupReady()?`${esc(Quiz.scopes[config.scope])} · 난이도 ${Quiz.levels[config.level].name} · ${config.count}문제 · 100점 만점`:'위에서 세 가지를 고르면 준비 완료!'}</p><button class="primary" id="start"${setupReady()?'':' hidden'}><span>선수 맞히기 시작</span><span aria-hidden="true">→</span></button></div></section>`;}
function bindSetup(){document.querySelectorAll('[data-choice]').forEach(button=>button.onclick=()=>{
 const key=button.dataset.choice,value=button.dataset.value;config={...config,[key]:key==='count'?Number(value):value};chosen[key]=true;
 if(shared){shared=false;history.replaceState(null,'',location.pathname+location.search);}
 landing();document.querySelector(`[data-choice="${key}"][data-value="${value}"]`).focus();
});}
function goHome(){quickEntry=false;stopTimer();shared=false;history.replaceState(null,'',location.pathname+location.search);index=0;extra=0;locked=false;results=[];landing();window.scrollTo(0,0);}
function quit(){if(index===0&&extra===0&&!locked){goHome();return;}if(window.confirm('진행 중인 점수는 저장되지 않습니다. 포기하고 처음으로 돌아갈까요?'))goHome();}
function landing(){document.body.dataset.screen="setup";stopTimer();const size=Quiz.pool(data,config.scope).length;app.innerHTML=`<section class="hero lobby-hero"><p class="eyebrow">기록 속 주인공을 찾아라</p><h1>나는 <em>누구일까요?</em></h1><p>힌트를 읽고 네 명 중 한 선수를 골라 주세요.<br>전북에서의 활약, 시즌 기록, 골과 도움.<br>그라운드 위 기록으로 선수를 맞혀 보세요.</p><div class="meta"${setupReady()?'':' hidden'}><span class="tag">${esc(Quiz.scopes[config.scope])}</span><span class="tag">난이도 ${Quiz.levels[config.level].name}</span></div></section>${setupControls()}<div class="stats"${setupReady()?'':' hidden'}><div class="stat"><strong>${config.count}</strong><span>문제</span></div><div class="stat"><strong>${Quiz.levels[config.level].hints}</strong><span>기본 힌트</span></div><div class="stat"><strong>${100/config.count}</strong><span>문제당 최고 점수</span></div></div><section class="panel rules-panel"><details><summary>게임 방법 · 출제 기준</summary><ul class="rules"><li>4지선다 · 답을 고르면 정답과 점수를 확인합니다. 다음 문제 버튼을 누르면 진행합니다.</li><li>모든 도전은 100점 만점입니다. 5문제는 문제당 20점, 10문제는 10점, 20문제는 5점입니다. 추가 힌트는 해당 문항 배점의 하 25% · 중 약 16.7% · 상 12.5%씩 감점하며 정답 최소 점수에도 같은 비율을 적용합니다. 오답·건너뛰기는 0점입니다.</li><li>시간 제한 없이 풀 수 있습니다. 추가 힌트는 아래로 이어서 표시됩니다.</li><li>게임 종료 후 닉네임을 입력하고 확인하면 댓글용 결과가 복사됩니다. 게임 링크는 포함하지 않습니다.</li></ul><details><summary>출제 기준과 데이터 보기</summary><p class="muted">현재 명단: ${esc(data.asOf)} · ${data.season}시즌. 이 범위에서 출제 가능한 선수 ${size}명.<br>역대 범위는 공식 전북 역대 검색과 보유 선수의 전북 시즌 기록을 합쳤습니다. 힌트가 5개 이상 있는 선수만 출제하며, 등록만 하고 기록이 없는 선수 등은 누락될 수 있습니다.<br>경력 힌트는 K리그에 기록된 팀이며 해외·아마추어 전체 경력을 뜻하지 않습니다. 생년월일·키·국적은 새 문제의 힌트로 사용하지 않습니다. 포지션·등록 구단·등번호와 축구 기록만 사용합니다. 출장·득점·도움·골키퍼 실점/클린시트는 K리그1·2를 구분하며 컵·플레이오프를 제외합니다. 이적 선수의 같은 시즌 기록은 소속 팀별 기록을 합산합니다. 올 시즌 기록이 없으면 마지막 기록 시즌을 연도와 함께 표시합니다.</p></details></details></section>`;document.querySelector('.lobby-setup').append(document.querySelector('.rules-panel'));bindSetup();document.querySelector('#start').onclick=()=>{if(!setupReady())return;if(!shared)config={...config,seed:crypto.getRandomValues(new Uint32Array(1))[0]};deck=Quiz.questions(data,config);index=0;results=[];renderQuestion();};}
function renderQuestion(){document.body.dataset.screen="question";stopTimer();locked=false;extra=0;const q=deck[index];app.innerHTML=`<button class="home-button" id="quit">${index===0&&!results.length?'범위·난이도 바꾸기':'← 포기하고 설정으로'}</button><div class="question-top"><span>${esc(subtitle())}</span><span>${index+1} / ${deck.length}</span></div><div class="progress"><i style="width:${index/deck.length*100}%"></i></div><p class="eyebrow">QUESTION ${String(index+1).padStart(2,'0')}</p><h1 class="question-title">${quickEntry&&index===0?'전북팬이라면, 이 선수는?':'이 선수는 누구일까요?'}</h1><section class="panel"><dl id="hints"></dl><p class="muted">${q.answer.statsAsOf?`기록 수집 ${esc(q.answer.statsAsOf)} · `:''}시즌별 기록은 표시된 연도 기준 · 컵·플레이오프 제외</p><div class="actions"><button id="hint">힌트 하나 더 보기</button><span class="muted" id="available"></span></div></section><div class="options">${q.options.map((p,i)=>`<button class="option" data-id="${p.id}"><span>${String(i+1).padStart(2,'0')}</span>${esc(p.name)}</button>`).join('')}</div><button id="skip">모르겠어요 · 건너뛰기</button><section id="feedback" role="status"></section>`;
 document.querySelector('#quit').onclick=quit;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(b.dataset.id));document.querySelector('#skip').onclick=()=>answer(null);document.querySelector('#hint').onclick=()=>{if(!locked){extra++;renderHints();}};renderHints();window.scrollTo(0,0);}
function renderHints(){const q=deck[index],n=Math.min(q.hints.length,Quiz.levels[config.level].hints+extra);document.querySelector('#hints').innerHTML=q.hints.slice(0,n).map(h=>`<div class="hint"><dt>${esc(h[0])}</dt><dd>${esc(h[1])}</dd></div>`).join('');document.querySelector('#available').textContent=`정답 ${displayedScore(Quiz.points(extra,true,config.level))}점 · ${n}/${q.hints.length}개 공개`;document.querySelector('#hint').disabled=locked||n===q.hints.length;document.querySelector('#hint').textContent=`힌트 하나 더 보기 −${displayedScore(Quiz.points(extra,true,config.level)-Quiz.points(extra+1,true,config.level))}점`;}
function answer(id){if(locked)return;locked=true;const q=deck[index],correct=id===q.answer.id,points=Quiz.points(extra,correct,config.level);results.push({id:q.answer.id,name:q.answer.name,correct,points,extra,skipped:id===null,source:q.answer.source});document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.id===q.answer.id)b.classList.add('correct');else if(b.dataset.id===id)b.classList.add('wrong');});document.querySelector('#hint').disabled=true;document.querySelector('#skip').hidden=true;document.querySelector('#feedback').innerHTML=`<div class="answer"><h2>${correct?'정답입니다!':'아쉽지만, 정답은…'}</h2><p><strong>${esc(q.answer.name)}</strong> · ${displayedScore(points)}점</p></div><button class="primary" id="next">${index+1===deck.length?'최종 점수 보기':'다음 문제 →'}</button>`;document.querySelector('#next').onclick=advanceQuestion;document.querySelector('#next').focus();}
function advanceQuestion(){stopTimer();index++;if(index===deck.length)finish();else renderQuestion();}
function scoreText(){const total=results.reduce((n,r)=>n+r.points,0);return `닉네임: ${playerName}\n게임 종류: 선수 맞히기 · ${Quiz.scopes[config.scope]}\n난이도: ${Quiz.levels[config.level].name}\n문제 수: ${deck.length}문제\n점수: ${displayedScore(total)} / 100점`;}
async function copyResult(){const input=document.querySelector('#nickname');try{playerName=Quiz.nickname(input.value);input.value=playerName;input.removeAttribute('aria-invalid');document.querySelector('#copy-status').textContent='';}catch(e){document.querySelector('#copy-status').textContent=e.message;input.setAttribute('aria-invalid','true');input.focus();return;}document.querySelector('#copy-fallback').hidden=true;try{await navigator.clipboard.writeText(scoreText());document.querySelector('#copy-status').textContent='복사했어요. 댓글 입력란에 붙여넣으세요.';}catch{document.querySelector('#copy-fallback').hidden=false;const t=document.querySelector('#copy-text');t.value=scoreText();t.focus();t.select();document.querySelector('#copy-status').textContent='자동 복사가 차단되어 내용을 선택했어요. 직접 복사해 댓글에 붙여넣으세요.';}}
function finish(){document.body.dataset.screen="result";stopTimer();const total=results.reduce((n,r)=>n+r.points,0),correct=results.filter(r=>r.correct).length;app.innerHTML=`<section class="hero"><p class="eyebrow">FULL TIME · 도전 완료</p><h1>당신의 축구력,<br><em>오늘의 결과는?</em></h1><p>${esc(subtitle())}</p></section><section class="panel"><div class="score">${displayedScore(total)}<small> / 100점</small></div><p>${correct} / ${deck.length} 정답 · 정답률 ${Math.round(correct/deck.length*100)}%</p><div class="tiles">${results.map(r=>r.correct?(r.extra?'🟨':'🟩'):'⬜').join('')}</div><p class="muted">🟩 기본 힌트로 정답 · 🟨 추가 힌트 후 정답 · ⬜ 오답/건너뛰기</p><div class="nickname-field"><label for="nickname">닉네임</label><input id="nickname" type="text" maxlength="20" autocomplete="off" placeholder="댓글에 표시할 닉네임" value="${esc(playerName)}" aria-describedby="copy-status"><small>닉네임을 입력하고 확인하면 댓글용 결과가 복사됩니다.</small></div><div class="actions"><button class="primary" id="copy-result">확인 · 결과 복사</button><button id="home">처음으로 · 설정 바꾸기</button></div><p id="copy-status" role="status"></p><div id="copy-fallback" hidden><label>공유할 결과<textarea class="fallback" id="copy-text" readonly></textarea></label></div></section><section class="panel"><h2>오늘 만난 선수들</h2>${results.map((r,i)=>`<div class="review"><span>${i+1}. <a href="${esc(r.source)}" target="_blank" rel="noopener">${esc(r.name)}</a></span><span>${r.correct?'정답':r.skipped?'건너뜀':'오답'} · ${displayedScore(r.points)}점</span></div>`).join('')}<p class="muted">100점 만점 · 추가 힌트 감점 반영. 합산 후 소수 첫째 자리로 반올림하므로 문항별 표시 점수의 합과 다를 수 있습니다. 같은 범위·난이도·문제 수끼리 비교해 주세요. 닉네임과 점수는 서버에 저장하지 않습니다. 복사한 결과를 댓글로 공유해 주세요.</p></section>`;document.querySelector('#home').onclick=goHome;document.querySelector('#copy-result').onclick=copyResult;document.querySelector('#nickname').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();copyResult();}};window.scrollTo(0,0);}
(async()=>{try{const raw=new URLSearchParams(location.hash.slice(1)).get('q');if(raw){config=Quiz.decode(raw);shared=true;chosen={scope:true,level:true,count:true};}else {const manifest=await getJSON('data/manifest.json');config=Quiz.validate({v:1,data:manifest.version,scope:'jb',level:'easy',count:5,seed:crypto.getRandomValues(new Uint32Array(1))[0]});}data=await getJSON(`data/${config.data}.json`);if(shared){deck=Quiz.questions(data,config);landing();}else{quickEntry=true;deck=Quiz.questions(data,config,true);renderQuestion();}}catch(e){app.innerHTML=`<section class="panel"><h1 class="question-title">게임을 열 수 없어요</h1><p class="error">${esc(e.message)}</p><a class="button" href="./">기본 도전으로 이동</a></section>`;}})();
window.addEventListener('hashchange',()=>location.reload());


