'use strict';
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config,data,deck,index=0,extra=0,locked=false,results=[];
const safePhoto=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:'';}catch{return '';}};
async function getJSON(url){const r=await fetch(url);if(!r.ok)throw Error('출제 데이터를 불러오지 못했습니다. 잠시 후 새로고침해 주세요.');return r.json();}
function subtitle(){return `${Quiz.scopes[config.scope]} · 난이도 ${Quiz.levels[config.level].name} · ${config.count}문제`;}
function gameURL(){const u=new URL('./',location.href);u.hash='q='+Quiz.encode(config);return u.href;}
function landing(){const size=Quiz.pool(data,config.scope).length;app.innerHTML=`<section class="hero"><p class="eyebrow">기록 속 주인공을 찾아라</p><h1>나는<br><em>누구일까요?</em></h1><p>힌트를 읽고 네 명 중 한 선수를 골라 주세요.<br>당신은 K리그를 얼마나 알고 있나요?</p><div class="meta"><span class="tag">${esc(Quiz.scopes[config.scope])}</span><span class="tag">난이도 ${Quiz.levels[config.level].name}</span></div></section><div class="stats"><div class="stat"><strong>${config.count}</strong><span>문제</span></div><div class="stat"><strong>${Quiz.levels[config.level].hints}</strong><span>기본 힌트</span></div><div class="stat"><strong>100</strong><span>문제당 최고 점수</span></div></div><section class="panel"><button class="primary" id="start">선수 맞히기 시작 →</button><ul class="rules"><li>4지선다 · 문제마다 한 번만 답할 수 있습니다.</li><li>추가 힌트 1개당 20점 감점, 정답은 최소 20점입니다.</li><li>오답·건너뛰기는 0점. 시간에 따른 감점은 없습니다.</li><li>같은 도전 링크는 같은 문제와 보기 순서입니다.</li></ul><details><summary>출제 기준과 데이터 보기</summary><p class="muted">현재 명단: ${esc(data.asOf)} · ${data.season}시즌. 이 범위에서 출제 가능한 선수 ${size}명.<br>역대 범위는 공식 전북 역대 검색과 보유 선수의 전북 시즌 기록을 합쳤습니다. 힌트가 5개 이상 있는 선수만 출제하며, 등록만 하고 기록이 없는 선수 등은 누락될 수 있습니다.<br>경력 힌트는 K리그에 기록된 팀이며 해외·아마추어 전체 경력을 뜻하지 않습니다. 과거 선수의 정보는 공식 프로필에 남은 값입니다.</p></details></section>`;document.querySelector('#start').onclick=()=>{index=0;results=[];renderQuestion();};}
function renderQuestion(){locked=false;extra=0;const q=deck[index];app.innerHTML=`<div class="question-top"><span>${esc(subtitle())}</span><span>${index+1} / ${deck.length}</span></div><div class="progress"><i style="width:${index/deck.length*100}%"></i></div><p class="eyebrow">QUESTION ${String(index+1).padStart(2,'0')}</p><h1 class="question-title">이 선수는 누구일까요?</h1><section class="panel"><dl id="hints"></dl><div class="actions"><button id="hint">힌트 하나 더 보기 −20점</button><span class="muted" id="available"></span></div></section><div class="options">${q.options.map((p,i)=>`<button class="option" data-id="${p.id}"><span>${String(i+1).padStart(2,'0')}</span>${esc(p.name)}</button>`).join('')}</div><button id="skip">모르겠어요 · 건너뛰기</button><section id="feedback" role="status"></section>`;
 document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(b.dataset.id));document.querySelector('#skip').onclick=()=>answer(null);document.querySelector('#hint').onclick=()=>{if(!locked){extra++;renderHints();}};renderHints();window.scrollTo(0,0);}
function renderHints(){const q=deck[index],n=Math.min(q.hints.length,Quiz.levels[config.level].hints+extra);document.querySelector('#hints').innerHTML=q.hints.slice(0,n).map(h=>`<div class="hint"><dt>${esc(h[0])}</dt><dd>${esc(h[1])}</dd></div>`).join('');document.querySelector('#available').textContent=`지금 맞히면 ${Quiz.points(extra,true)}점 · 힌트 ${n}/${q.hints.length}`;document.querySelector('#hint').disabled=locked||n===q.hints.length;}
function answer(id){if(locked)return;locked=true;const q=deck[index],correct=id===q.answer.id,points=Quiz.points(extra,correct);results.push({id:q.answer.id,name:q.answer.name,correct,points,extra,skipped:id===null,source:q.answer.source});document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.id===q.answer.id)b.classList.add('correct');else if(b.dataset.id===id)b.classList.add('wrong');});document.querySelector('#hint').disabled=true;document.querySelector('#skip').hidden=true;
 const photo=safePhoto(q.answer.photo);document.querySelector('#feedback').innerHTML=`<div class="answer">${photo?`<img src="${esc(photo)}" alt="${esc(q.answer.name)} 선수 사진" loading="lazy">`:''}<h2>${correct?'정답입니다!':id===null?'다음엔 맞힐 수 있어요.':'아쉽지만, 정답은…'}</h2><p><strong>${esc(q.answer.name)}</strong> · ${points}점</p><a href="${esc(q.answer.source)}" target="_blank" rel="noopener">공식 선수 기록 확인 ↗</a><details><summary>모든 힌트 확인</summary>${q.hints.map(h=>`<p class="muted">${esc(h[0])}: ${esc(h[1])}</p>`).join('')}</details></div><button class="primary" id="next">${index+1===deck.length?'최종 점수 보기':'다음 문제 →'}</button>`;const img=document.querySelector('#feedback img');if(img)img.onerror=()=>img.remove();document.querySelector('#next').onclick=()=>{index++;if(index===deck.length)finish();else renderQuestion();};document.querySelector('#next').focus();}
function scoreText(){const total=results.reduce((n,r)=>n+r.points,0),correct=results.filter(r=>r.correct).length;return `⚽ 나는 누구일까요?\n${subtitle()}\n${total} / ${deck.length*100}점 · ${correct}/${deck.length} 정답\n${results.map(r=>r.correct?(r.extra?'🟨':'🟩'):'⬜').join('')}\n🟩 힌트 추가 없이 정답 · 🟨 추가 힌트 후 정답\n같은 문제에 도전해 보세요!\n${gameURL()}`;}
async function copyResult(){try{await navigator.clipboard.writeText(scoreText());document.querySelector('#copy-status').textContent='결과와 도전 링크를 복사했어요. 원하는 곳에 붙여넣으세요.';}catch{document.querySelector('#copy-fallback').hidden=false;const t=document.querySelector('#copy-text');t.value=scoreText();t.focus();t.select();document.querySelector('#copy-status').textContent='자동 복사를 사용할 수 없어 텍스트를 선택했어요. 직접 복사해 주세요.';}}
function finish(){const total=results.reduce((n,r)=>n+r.points,0),correct=results.filter(r=>r.correct).length;app.innerHTML=`<section class="hero"><p class="eyebrow">FULL TIME · 도전 완료</p><h1>당신의 축구력,<br><em>오늘의 결과는?</em></h1><p>${esc(subtitle())}</p></section><section class="panel"><div class="score">${total}<small> / ${deck.length*100}점</small></div><p>${correct} / ${deck.length} 정답 · 정답률 ${Math.round(correct/deck.length*100)}%</p><div class="tiles">${results.map(r=>r.correct?(r.extra?'🟨':'🟩'):'⬜').join('')}</div><p class="muted">🟩 기본 힌트로 정답 · 🟨 추가 힌트 후 정답 · ⬜ 오답/건너뛰기</p><div class="actions"><button class="primary" id="copy-result">내 결과 복사 ↗</button><button id="retry">같은 문제 다시 풀기</button></div><p id="copy-status" role="status"></p><div id="copy-fallback" hidden><label>공유할 결과<textarea class="fallback" id="copy-text" readonly></textarea></label></div></section><section class="panel"><h2>오늘 만난 선수들</h2>${results.map((r,i)=>`<div class="review"><span>${i+1}. <a href="${esc(r.source)}" target="_blank" rel="noopener">${esc(r.name)}</a></span><span>${r.correct?'정답':r.skipped?'건너뜀':'오답'} · ${r.points}점</span></div>`).join('')}<p class="muted">다른 난이도·범위의 점수는 직접 비교하기 어렵습니다. 같은 링크로 도전한 친구와 비교해 주세요.</p></section>`;document.querySelector('#copy-result').onclick=copyResult;document.querySelector('#retry').onclick=()=>{index=0;results=[];renderQuestion();};window.scrollTo(0,0);}
(async()=>{try{const raw=new URLSearchParams(location.hash.slice(1)).get('q');if(raw)config=Quiz.decode(raw);else {const manifest=await getJSON('data/manifest.json');config=Quiz.validate({v:1,data:manifest.version,scope:'jb',level:'normal',count:10,seed:20260916});}data=await getJSON(`data/${config.data}.json`);deck=Quiz.questions(data,config);landing();}catch(e){app.innerHTML=`<section class="panel"><h1 class="question-title">게임을 열 수 없어요</h1><p class="error">${esc(e.message)}</p><a class="button" href="./">기본 도전으로 이동</a></section>`;}})();
window.addEventListener('hashchange',()=>location.reload());
