'use strict';
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config,data,deck,index=0,extra=0,locked=false,results=[],shared=false,chosen={scope:false,level:false,count:false};
const QUESTION_MS=10000;
let timerId=null,advanceId=null,deadline=0,wallDeadline=0;
function stopTimer(){if(timerId!==null)clearInterval(timerId);timerId=null;if(advanceId!==null)clearTimeout(advanceId);advanceId=null;}
function remainingTime(){return Math.max(0,Math.min(deadline-performance.now(),wallDeadline-Date.now()));}
function paintTimer(remaining){const bar=document.querySelector('#time-fill');if(!bar)return;bar.style.transform=`scaleX(${remaining/QUESTION_MS})`;bar.classList.toggle('urgent',remaining<=1500);}
function tickTimer(){if(locked)return;const remaining=remainingTime();paintTimer(remaining);if(remaining<=0)answer(null,true);}
function startTimer(){stopTimer();deadline=performance.now()+QUESTION_MS;wallDeadline=Date.now()+QUESTION_MS;paintTimer(QUESTION_MS);timerId=setInterval(tickTimer,40);}
const safePhoto=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:'';}catch{return '';}};
async function getJSON(url){const r=await fetch(url);if(!r.ok)throw Error('출제 데이터를 불러오지 못했습니다. 잠시 후 새로고침해 주세요.');return r.json();}
function subtitle(){return `${Quiz.scopes[config.scope]} · 난이도 ${Quiz.levels[config.level].name} · ${config.count}문제 · 문제당 10초`;}
function gameURL(){const u=new URL('./',location.href);u.hash='q='+Quiz.encode(config);return u.href;}
function setupReady(){return Object.values(chosen).every(Boolean);}
const scopeCards={jb:['전북 현대','지금의 녹색 전사들','CURRENT SQUAD','shield'],history:['역대 전북','추억 속 레전드까지','ALL-TIME JEONBUK','star'],k1:['K리그1','1부 리그를 누비는 선수들','K LEAGUE 1','ball'],all:['K리그1 + K리그2','두 리그를 아우르는 축구력','ALL LEAGUES','pitch']};
const icons={shield:'<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6Z"/><path d="m8 12 3 3 5-6"/>',star:'<path d="m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',ball:'<circle cx="12" cy="12" r="9"/><path d="m12 7 5 4-2 6H9l-2-6Z M12 3v4m9 4-4 0m-2 6 3 3M9 17l-3 3M7 11l-4 0"/>',pitch:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16M3 9h4v6H3m18-6h-4v6h4"/><circle cx="12" cy="12" r="3"/>'};
function choiceContent(key,value){
 if(key==='scope'){const [name,desc,kicker,icon]=scopeCards[value];return `<span class="card-top"><span class="scope-symbol"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${icons[icon]}</svg></span><span class="card-kicker">${kicker}</span></span><strong class="card-title">${name}</strong><span class="card-description">${desc}</span><span class="card-foot">${Quiz.pool(data,value).length}명의 선수 <span aria-hidden="true">↗</span></span>`;}
 if(key==='level'){const l=Quiz.levels[value],descs={easy:'가볍게 몸풀기',normal:'팬심을 시험하기',hard:'진짜 고수라면'};return `<span class="difficulty-name">${l.name}<span>난이도</span></span><span class="hint-dots" aria-hidden="true">${[1,2,3,4,5].map(n=>`<i class="${n<=l.hints?'lit':''}"></i>`).join('')}</span><strong class="level-description">${descs[value]}</strong><span class="card-description">처음부터 힌트 ${l.hints}개</span>`;}
 const descs={5:'워밍업',10:'한 판 승부',20:'풀타임 도전'};return `<span class="count-number">${String(value).padStart(2,'0')}<small>문제</small></span><span class="card-description">${descs[value]}</span>`;
}
function choiceGroup(key,number,title,subtitle,values){return `<section class="choice-group group-${key}" role="group" aria-label="${esc(title)}"><div class="group-heading"><span class="step-number">${number}</span><span>${title}<small>${subtitle}</small></span>${chosen[key]?'<span class="step-done">선택 완료 ✓</span>':''}</div><div class="choice-options ${key==='scope'?'scope-options':''}">${values.map(value=>{const active=chosen[key]&&String(config[key])===String(value);return `<button type="button" class="choice${active?' selected':''}" data-choice="${key}" data-value="${value}" aria-pressed="${active}"><span class="choice-check" aria-hidden="true">${active?'✓':''}</span>${choiceContent(key,value)}</button>`;}).join('')}</div></section>`;}
function setupControls(){const count=Object.values(chosen).filter(Boolean).length;return `<section class="setup lobby-setup"><div class="setup-heading"><p class="eyebrow">MATCH SETUP</p><span class="setup-counter">${count}<span> / 3</span></span></div>${choiceGroup('scope','01','누구를 맞혀볼까요?','내가 아는 선수들이 있는 무대를 선택하세요.',Object.keys(Quiz.scopes))}${choiceGroup('level','02','얼마나 자신 있나요?','어떤 난이도든 생각할 시간은 10초.',Object.keys(Quiz.levels))}${choiceGroup('count','03','몇 문제에 도전할까요?','원하는 길이로 한 판 즐겨보세요.',[5,10,20])}<div class="start-zone"><p id="setup-status">${setupReady()?`${esc(Quiz.scopes[config.scope])} · 난이도 ${Quiz.levels[config.level].name} · ${config.count}문제`:'위에서 세 가지를 고르면 준비 완료!'}</p><button class="primary" id="start"${setupReady()?'':' hidden'}><span>선수 맞히기 시작</span><span aria-hidden="true">→</span></button></div></section>`;}
function bindSetup(){document.querySelectorAll('[data-choice]').forEach(button=>button.onclick=()=>{
 const key=button.dataset.choice,value=button.dataset.value;config={...config,[key]:key==='count'?Number(value):value};chosen[key]=true;
 if(shared){shared=false;history.replaceState(null,'',location.pathname+location.search);}
 landing();document.querySelector(`[data-choice="${key}"][data-value="${value}"]`).focus();
});}
function goHome(){stopTimer();index=0;extra=0;locked=false;results=[];landing();window.scrollTo(0,0);}
function quit(){if(window.confirm('진행 중인 점수는 저장되지 않습니다. 포기하고 처음으로 돌아갈까요?'))goHome();}
function landing(){document.body.dataset.screen="setup";stopTimer();const size=Quiz.pool(data,config.scope).length;app.innerHTML=`<section class="hero lobby-hero"><p class="eyebrow">기록 속 주인공을 찾아라</p><h1>나는 <em>누구일까요?</em></h1><p>힌트를 읽고 네 명 중 한 선수를 골라 주세요.<br>전북에서의 활약, 시즌 기록, 골과 도움.<br>그라운드 위 기록으로 선수를 맞혀 보세요.</p><div class="meta"${setupReady()?'':' hidden'}><span class="tag">${esc(Quiz.scopes[config.scope])}</span><span class="tag">난이도 ${Quiz.levels[config.level].name}</span></div></section>${setupControls()}<div class="stats"${setupReady()?'':' hidden'}><div class="stat"><strong>${config.count}</strong><span>문제</span></div><div class="stat"><strong>${Quiz.levels[config.level].hints}</strong><span>기본 힌트</span></div><div class="stat"><strong>100</strong><span>문제당 최고 점수</span></div></div><section class="panel rules-panel"><details><summary>게임 방법 · 출제 기준</summary><ul class="rules"><li>4지선다 · 정답·오답·시간 초과 모두 결과를 2초간 보여준 뒤 다음 선수로 넘어갑니다.</li><li>추가 힌트 1개당 20점 감점, 정답은 최소 20점입니다.</li><li>문제당 10초! 시간 바가 사라지면 실패·0점입니다. 힌트를 열어도 시간은 계속 흐릅니다.</li><li>결과에 담긴 도전 링크는 같은 설정으로 시작하면 같은 문제와 보기 순서입니다. 설정은 참가자가 바꿀 수 있습니다.</li></ul><details><summary>출제 기준과 데이터 보기</summary><p class="muted">현재 명단: ${esc(data.asOf)} · ${data.season}시즌. 이 범위에서 출제 가능한 선수 ${size}명.<br>역대 범위는 공식 전북 역대 검색과 보유 선수의 전북 시즌 기록을 합쳤습니다. 힌트가 5개 이상 있는 선수만 출제하며, 등록만 하고 기록이 없는 선수 등은 누락될 수 있습니다.<br>경력 힌트는 K리그에 기록된 팀이며 해외·아마추어 전체 경력을 뜻하지 않습니다. 생년월일·키·국적은 새 문제의 힌트로 사용하지 않습니다. 포지션·등록 구단·등번호와 축구 기록만 사용합니다. 출장·득점·도움·골키퍼 실점/클린시트는 K리그1·2를 구분하며 컵·플레이오프를 제외합니다. 이적 선수의 같은 시즌 기록은 소속 팀별 기록을 합산합니다. 올 시즌 기록이 없으면 마지막 기록 시즌을 연도와 함께 표시합니다.</p></details></details></section>`;bindSetup();document.querySelector('#start').onclick=()=>{if(!setupReady())return;if(!shared)config={...config,seed:crypto.getRandomValues(new Uint32Array(1))[0]};deck=Quiz.questions(data,config);index=0;results=[];renderQuestion();};}
function renderQuestion(){document.body.dataset.screen="question";stopTimer();locked=false;extra=0;const q=deck[index];app.innerHTML=`<button class="home-button" id="quit">← 포기하고 처음으로</button><div class="question-top"><span>${esc(subtitle())}</span><span>${index+1} / ${deck.length}</span></div><div class="progress"><i style="width:${index/deck.length*100}%"></i></div><p class="eyebrow">QUESTION ${String(index+1).padStart(2,'0')}</p><h1 class="question-title">이 선수는 누구일까요?</h1><div class="time-header"><span>시간 안에 선택하세요</span><span id="time-state">생각할 시간</span></div><div class="time-track" role="img" aria-label="10초 제한시간이 줄어드는 바"><div id="time-fill"></div></div><section class="panel"><dl id="hints"></dl><p class="muted">${q.answer.statsAsOf?`기록 수집 ${esc(q.answer.statsAsOf)} · `:''}시즌별 기록은 표시된 연도 기준 · 컵·플레이오프 제외</p><div class="actions"><button id="hint">힌트 하나 더 보기 −20점</button><span class="muted" id="available"></span></div></section><div class="options">${q.options.map((p,i)=>`<button class="option" data-id="${p.id}"><span>${String(i+1).padStart(2,'0')}</span>${esc(p.name)}</button>`).join('')}</div><button id="skip">모르겠어요 · 건너뛰기</button><section id="feedback" role="status"></section>`;
 document.querySelector('#quit').onclick=quit;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(b.dataset.id));document.querySelector('#skip').onclick=()=>answer(null);document.querySelector('#hint').onclick=()=>{if(!locked){if(remainingTime()<=0){answer(null,true);return;}extra++;renderHints();}};renderHints();window.scrollTo(0,0);startTimer();}
function renderHints(){const q=deck[index],n=Math.min(q.hints.length,Quiz.levels[config.level].hints+extra);document.querySelector('#hints').innerHTML=q.hints.slice(0,n).map(h=>`<div class="hint"><dt>${esc(h[0])}</dt><dd>${esc(h[1])}</dd></div>`).join('');document.querySelector('#available').textContent=`지금 맞히면 ${Quiz.points(extra,true)}점 · 힌트 ${n}/${q.hints.length}`;document.querySelector('#hint').disabled=locked||n===q.hints.length;}
function answer(id,timedOut=false){if(locked)return;if(timedOut||remainingTime()<=0){timedOut=true;id=null;}document.querySelector('#time-fill').style.transition='none';paintTimer(timedOut?0:remainingTime());stopTimer();locked=true;document.querySelector('#time-state').textContent=timedOut?'시간 초과':'답변 완료';const q=deck[index],correct=id===q.answer.id,points=Quiz.points(extra,correct);results.push({id:q.answer.id,name:q.answer.name,correct,points,extra,timedOut,skipped:id===null&&!timedOut,source:q.answer.source});document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.id===q.answer.id)b.classList.add('correct');else if(b.dataset.id===id)b.classList.add('wrong');});document.querySelector('#hint').disabled=true;document.querySelector('#skip').hidden=true;
 const photo=safePhoto(q.answer.photo);document.querySelector('#feedback').innerHTML=`<div class="answer">${photo?`<img src="${esc(photo)}" alt="${esc(q.answer.name)} 선수 사진" loading="lazy">`:''}<h2>${timedOut?'시간 초과! 아쉽지만, 정답은…':correct?'정답입니다!':id===null?'아쉽지만, 정답은…':'아쉽지만, 정답은…'}</h2><p><strong>${esc(q.answer.name)}</strong> · ${points}점</p><a href="${esc(q.answer.source)}" target="_blank" rel="noopener">공식 선수 기록 확인 ↗</a><details><summary>모든 힌트 확인</summary>${q.hints.map(h=>`<p class="muted">${esc(h[0])}: ${esc(h[1])}</p>`).join('')}</details></div><p class="muted">2초 후 ${index+1===deck.length?'최종 점수로':'다음 선수로'} 자동으로 넘어갑니다.</p>`;const img=document.querySelector('#feedback img');if(img)img.onerror=()=>img.remove();document.querySelector('#feedback').setAttribute('tabindex','-1');document.querySelector('#feedback').focus();advanceId=setTimeout(advanceQuestion,2000);}
function advanceQuestion(){stopTimer();index++;if(index===deck.length)finish();else renderQuestion();}
function scoreText(){const total=results.reduce((n,r)=>n+r.points,0),correct=results.filter(r=>r.correct).length;return `⚽ 나는 누구일까요?\n${subtitle()}\n${total} / ${deck.length*100}점 · ${correct}/${deck.length} 정답\n${results.map(r=>r.correct?(r.extra?'🟨':'🟩'):'⬜').join('')}\n🟩 힌트 추가 없이 정답 · 🟨 추가 힌트 후 정답\n같은 문제에 도전해 보세요!\n${gameURL()}`;}
async function copyResult(){try{await navigator.clipboard.writeText(scoreText());document.querySelector('#copy-status').textContent='결과와 도전 링크를 복사했어요. 원하는 곳에 붙여넣으세요.';}catch{document.querySelector('#copy-fallback').hidden=false;const t=document.querySelector('#copy-text');t.value=scoreText();t.focus();t.select();document.querySelector('#copy-status').textContent='자동 복사를 사용할 수 없어 텍스트를 선택했어요. 직접 복사해 주세요.';}}
function finish(){document.body.dataset.screen="result";stopTimer();const total=results.reduce((n,r)=>n+r.points,0),correct=results.filter(r=>r.correct).length;app.innerHTML=`<section class="hero"><p class="eyebrow">FULL TIME · 도전 완료</p><h1>당신의 축구력,<br><em>오늘의 결과는?</em></h1><p>${esc(subtitle())}</p></section><section class="panel"><div class="score">${total}<small> / ${deck.length*100}점</small></div><p>${correct} / ${deck.length} 정답 · 정답률 ${Math.round(correct/deck.length*100)}%</p><div class="tiles">${results.map(r=>r.correct?(r.extra?'🟨':'🟩'):'⬜').join('')}</div><p class="muted">🟩 기본 힌트로 정답 · 🟨 추가 힌트 후 정답 · ⬜ 오답/건너뛰기/시간 초과</p><div class="actions"><button class="primary" id="copy-result">내 결과 복사 ↗</button><button id="retry">같은 문제 다시 풀기</button><button id="home">처음으로 · 설정 바꾸기</button></div><p id="copy-status" role="status"></p><div id="copy-fallback" hidden><label>공유할 결과<textarea class="fallback" id="copy-text" readonly></textarea></label></div></section><section class="panel"><h2>오늘 만난 선수들</h2>${results.map((r,i)=>`<div class="review"><span>${i+1}. <a href="${esc(r.source)}" target="_blank" rel="noopener">${esc(r.name)}</a></span><span>${r.timedOut?'시간 초과':r.correct?'정답':r.skipped?'건너뜀':'오답'} · ${r.points}점</span></div>`).join('')}<p class="muted">다른 난이도·범위의 점수는 직접 비교하기 어렵습니다. 같은 링크로 도전한 친구와 비교해 주세요.</p></section>`;document.querySelector('#home').onclick=goHome;document.querySelector('#copy-result').onclick=copyResult;document.querySelector('#retry').onclick=()=>{index=0;results=[];renderQuestion();};window.scrollTo(0,0);}
(async()=>{try{const raw=new URLSearchParams(location.hash.slice(1)).get('q');if(raw){config=Quiz.decode(raw);shared=true;chosen={scope:true,level:true,count:true};}else {const manifest=await getJSON('data/manifest.json');config=Quiz.validate({v:1,data:manifest.version,scope:'jb',level:'normal',count:10,seed:20260916});}data=await getJSON(`data/${config.data}.json`);deck=Quiz.questions(data,config);landing();}catch(e){app.innerHTML=`<section class="panel"><h1 class="question-title">게임을 열 수 없어요</h1><p class="error">${esc(e.message)}</p><a class="button" href="./">기본 도전으로 이동</a></section>`;}})();
window.addEventListener('hashchange',()=>location.reload());

document.addEventListener('visibilitychange',()=>{if(timerId!==null)tickTimer();});
